@startuml TEST_CLASS
/' Class elements 
with PlantUml '/

'===== PARAMS ====='
'skinparam responseMessageBelowArrow true
'skinparam sequenceMessageAlign center
'autonumber The keyword autonumber is used to automatically add an incrementing number to messages.

'====> Declaring element
/'
abstract abstract
abstract class "abstract class"
annotation annotation
circle circle
() circle_short_form
class class
class class_stereo <<stereotype>>
diamond diamond
'/

'====> Relations between classes
/'
Class01 <|-- Class02
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 -- Class10
'/
'====> Label on relations

class Client{
    -player
    -tcpSocket
    -ui_manager
    -parser
    +sendServer()
    +keyListener()
    +draw()
}

class Parser{
    +parseResponse()
    +stringifyMessage()
}

Class ui_manager{
    -matrice[]
    -colors[]
    +draw()
}

Class server{
    -tcpSocket[]
    -gameMatrix[]
    -verifier
    -computer
    +SendClient()
    +calculatePoints()
    +verifyWord
    +findWord()
}

Class Letter{
    -char
    -player
}

Class player{
    -nome
    -number
    -points
}
Client -- Parser
Client -- player
Client -- ui_manager
ui_manager -- Letter


server -- Parser
server -- ui_manager
server -- player
@enduml